version: '2'

services:

  master:
    image: vinsdocker/jmmaster
    container_name: master
    tty: true
    hostname: master
    networks:
      - vins
  slave:
    image: vinsdocker/jmserver
    tty: true
    networks:
      - vins
  
networks:
  vins:
    driver: bridge